name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a 'master' si usas esa rama
permissions:
  id-token: write
  pages: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Este paso configura las Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Este paso copia el contenido de 'ex00' a un artefacto
      - name: Build with specific directory
        run: |
          mkdir build
          cp -r ex00/* build/
          echo "Publicando desde ex00/"

      # Este paso sube el artefacto para su despliegue
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build' # Sube el contenido de la carpeta 'build'

      # Este paso despliega el sitio web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4